name: Build and Publish Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [created, published]
    tags:
      - 'v*'

jobs:
  build-rust:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: linux-binary
            exe_suffix: ""
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-src, rustc-dev, llvm-tools-preview

      - name: Install MUSL tools (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/canyon_uploader${{ matrix.exe_suffix }}

  publish-rust:
    needs: build-rust
    runs-on: ubuntu-latest
    # 仅在 release 事件下运行，避免其他触发条件下执行
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: release_artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Rust release built via GitHub Actions"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List release_artifacts directory contents
        run: |
          echo "Listing contents of release_artifacts directory:"
          ls -l release_artifacts

      - name: Upload linux release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_artifacts/canyon_uploader
          asset_name: linux-binary
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-pnpm:
    needs: publish-rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build PNPM project
        run: pnpm build

      - name: Upload PNPM Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-binary
          path: ./tools/canyon-extension/canyon-extension.zip  # 假设 PNPM 构建产物在 dist 目录，根据实际情况修改

  publish-pnpm:
    needs: build-pnpm
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download PNPM artifact
        uses: actions/download-artifact@v4
        with:
          name: pnpm-binary
          path: release_artifacts/pnpm

      - name: List release_artifacts directory contents
        run: |
          echo "Listing contents of release_artifacts directory:"
          ls -l release_artifacts

      - name: Upload PNPM release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: release_artifacts/pnpm
          asset_name: pnpm-binary
          asset_content_type: application/zip  # 根据实际情况修改内容类型
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
